[package]
name = "mylib-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["extra-traits"]}
quote = { workspace = true }
