[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"]}
quote = { workspace = true }
mylib-macro = { path = "../../mylib-macro" }

